FROM node:16 as build
ENV REACT_APP_API_URL /api
WORKDIR /usr/src/app
COPY . ./
RUN npm ci --only=production
RUN npm run build

FROM nginx:stable-alpine
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]