name: Test-branches

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm --prefix server ci
    - run: npm --prefix server run build --if-present
    - run: npm --prefix server test

    - run: npm --prefix client ci
    - run: npm --prefix client run build --if-present
    - run: npm --prefix client test